vehicle:
  inertia: [0.083541667, 0.03020833333, 0.1133333333]
  mass: 1.635
  motor_constant: 8.54858e-06
  max_rotor_vel: 1200

limits:
  max_thrust_one_motor: null  # This will be calculated
  max_thrust: 26.05 
  max_x_torque: 1.54816044
  max_y_torque: 3.46770732
  max_z_torque: 5.50050126

controller:
  mode: torque_thrust_setpoint
  type: nmpc_quat

states:
  type: 1
  position: [0, 0, 0]
  velocity: [0, 0, 0]
  attitude_quat: [0.5, -0.5, 0.5, 0.5]
  attitude_rot: [[0, -1, 0], [0, 0, 1], [-1, 0, 0]]
  angular_velocity: [0, 0, 0]

simulation:
  wind_velocity: [0, 0, 0]
  gravity: 9.81

desired:
  height: -20
  attitude_quat: [0.5, -0.5, 0.5, 0.5]
  attitude_rot: [[0, -1, 0], [0, 0, 1], [-1, 0, 0]]

nmpc:
  T: 1.0
  N: 20
  #best so far:
  # Q_quat: [2.0, 3.0, 5.0, 
  #          2.0, 2.0, 2.0,
  #          5.0, 3.5, 3.5]
  # Q_angle: 7.0
  # R: [0.0, 1.00, 2.5, 0.5]
  # R_var: [1.0, 0.04, 0.6, 0.04]

 # Q_quat_init: [8.0, 8.0, 80.0, 
  Q_quat_init: [8.0, 8.0, 150.0, #235
           3.0, 3.0, 40.0, #era 15, foi para 30
           7.0, 7.0, 7.0]
  Q_angle_init: [4.0, 1000.0]
  R_init: [0.5, 3.0, 3.0, 3.0]
  R_var_init: [0.0, 0.2, 0.2, 0.1]

  Q_quat_second: [0.0, 0.0, 00.0, 
           0.0, 0.0, 0.0,
           2.0, 2.0, 2.0]
  Q_angle_second: [7.0, 250.0]
  R_second: [0.25, 1.0, 2.5, 1.0]
  R_var_second: [0.0, 0.2, 0.2, 0.1]


  # Q_quat: [0.0, 0.0, 0.0, 
  #          2.0, 2.0, 2.0,
  #          5.0, 3.5, 3.5]
  # Q_angle: 19
  # R: [0.0, 4.00, 2.5, 2.5]
  # R_var: [1.0, 0.04, 0.6, 0.04]
  # Q_quat_hover: [0, 0, 0, 
  #          0, 0.0, 0.0,
  #          90.0,
  #          9, 9, 9]
  # Q_angle_hover: 2
  # R_hover: [0.0, 0.00, 0.00, 0.00]
  # R_var_hover : [0.05, 0.01, 0.01, 0.01]

pid:
  # height_p_gains: 8
  # height_i_gains: 6
  # height_d_gains: 10
  height_p_gains: 1
  height_i_gains: 2
  height_d_gains: 0.07
 # attitude_p_gains: [0.2, 3, 0.3]
  attitude_rates_p_gains: [0.4, 0.3, 0.25]
  attitude_rates_i_gains: [2, 2, 2]
  attitude_rates_d_gains: [0.005, 0.001, 0.001]

pid3:
  #funcionamndo ok antes de alterar a forma de calcular o alpha
  # height_p_gains: 0.6
  # height_i_gains: 0.9
  # height_d_gains: 0.0
  # attitude_p_gains: [0.3, 0.65, 2.0]
  # attitude_rates_p_gains: [0.1, 0.2, 0.50]
  # attitude_rates_i_gains: [0, 0.2, 0.2]
  # attitude_rates_d_gains: [0.0, 0.0, 0.0]

  #height_p_gains: 0.5
  #height_i_gains: 0.9
  #height_d_gains: 0.0
  height_p_gains: 4
  height_i_gains: 5
  height_d_gains: 6
  #attitude_p_gains: [0.4, 0.65, 2.0]
  #attitude_p_gains: [0.0, 1.3, 4.0]
  attitude_p_gains: [0.0, 1.5, 5.0]
  attitude_rates_p_gains: [0.1, 0.35, 0.50]
  attitude_rates_i_gains: [0.1, 0.2, 0.2]
  attitude_rates_d_gains: [0.0, 0.0, 0.0]